from sqlalchemy import BigInteger, Column, DateTime, String, Text, UniqueConstraint, func
from app.database import Base


class URL(Base):
    """
    Represents the 'urls' table in PostgreSQL.
    
    Columns:
    - id: 64-bit integer (BIGINT) generated by our Snowflake ID generator.
    - short_code: Base62 encoded string of the ID (e.g. '8WPnKG88RG0').
                  Marked UNIQUE to prevent duplicate short links.
    - original_url: The destination URL to redirect to.
    - created_at: Timestamp when this URL was shortened.
    """
    __tablename__ = "urls"

    # Snowflake ID is 64-bit, which maps to PostgreSQL BIGINT.
    # We disable autoincrement because our Snowflake generator supplies the IDs.
    id = Column(BigInteger, primary_key=True, autoincrement=False, index=True)

    # Short code with UNIQUE constraint and index for O(1) lookup
    short_code = Column(String(16), unique=True, index=True, nullable=False)

    # The original URL that users want to shorten
    original_url = Column(Text, nullable=False)

    # Automatically set to current timestamp on database insert
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Explicit UniqueConstraint for extra clarity and safety
    __table_args__ = (
        UniqueConstraint("short_code", name="uq_urls_short_code"),
    )

    def __repr__(self) -> str:
        return f"<URL id={self.id} short_code='{self.short_code}' original_url='{self.original_url}'>"


class ClickEvent(Base):
    """
    Represents the 'click_events' analytics table in PostgreSQL.
    Populated asynchronously by our RabbitMQ consumer worker.
    """
    __tablename__ = "click_events"

    id = Column(BigInteger, primary_key=True, autoincrement=True, index=True)
    short_code = Column(String(16), index=True, nullable=False)
    ip_address = Column(String(64), nullable=True)
    user_agent = Column(Text, nullable=True)
    referer = Column(Text, nullable=True)
    clicked_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    def __repr__(self) -> str:
        return f"<ClickEvent id={self.id} short_code='{self.short_code}' clicked_at={self.clicked_at}>"

